### ISSUE TITLE
entrust  setup tables not displayed in  database's table list

### ISSUE THREAD

**Issue by senthilkumar7915** [shanmuga3/laravel-entrust#1]
I have followed all your instruction .. all thinks are clear but I could not see 'permission', 'permission role', 'role'  in my database table.
![entrust](https://user-images.githubusercontent.com/62586074/79054297-5a7c7800-7c61-11ea-9704-bb257312b8d0.PNG)

**Comment by shanmuga3** [comment]
After run this command 
> php artisan laravel-entrust:setup

It will create entrust_setup_tables.php in migration folder, after than run 
> php artisan:migrate

to create tables. Can you see entrust_setup_tables.php in migrations folder.

**Comment by shanmuga3** [comment]
You Can refer this repo for reference. https://github.com/shanmuga3/laravel-blog
