### ISSUE TITLE
Undefined property: Shanmuga\LaravelEntrust\Middleware\LaravelEntrustAbility::$auth

### ISSUE THREAD

**Issue by bikash-s-bhandari** [shanmuga3/laravel-entrust#12]
Not able to use ability as middleware in laravel 9
 Route::get('',  ['as' => '',  'middleware' => ['ability:super-admin,student-index'],'uses' => 'StudentController@index']);

Error causing due to  
if ($this->auth->guest() || !$request->user()->ability($roles, $permissions, [ 'validate_all' => $validateAll ])) {
            return $this->unauthorized();
        }
In LaravelEnthrustAbility.php

**Comment by shanmuga3** [comment]
This issue is fixed, You can use dev-main to get updated
