### ISSUE TITLE
Call to undefined method getConnectionName

### ISSUE THREAD

**Issue by gomathisolai16** [shanmuga3/laravel-entrust#19]
After installing laravel version 10 am using this package for role management

**To Reproduce**
1. I have added this packge in Role model and extend it 
2. Added this package in Permission model and extend it 
3. added in config/app.php 
4. Modified Role management code 

**Expected behavior**
I should login based on Role

**Screenshots**
![image](https://github.com/shanmuga3/laravel-entrust/assets/9608876/4f3c3fff-adaf-4a3a-ad2d-833f5bd06669)

namespace App\Models;

use App\Additional\Models\Cachable;
use App\Schemes\Models\ICachable;
use Shanmuga\LaravelEntrust\Middleware\LaravelEntrustRole;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Role
 * @package App\Models
 */
class Role extends Model implements ICachable
{
    use Cachable;
    use LaravelEntrustRole;

    /**
     * @var array $fillable
     */
    protected $fillable = [
        'name', 'display_name', 'description'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function permissions(){
        return $this->belongsToMany(Permission::class,'id');
    }
    
}

**Comment by gomathisolai16** [comment]
@shanmuga3 Could  you please let me know any idea about this issue?

**Comment by shanmuga3** [comment]
it seems you have wrongly configured role Model. Role model should extend "EntrustRole" Model.  also attached sample code for your reference. if still you are facing the issue please attach complete role.php and permission.php files. Thank you

`<?php

namespace App\Models;

use Shanmuga\LaravelEntrust\Models\EntrustRole;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Role extends EntrustRole
{
	use HasFactory;
	
    /**
	* The attributes that aren't mass assignable.
	*
	* @var array
	*/
	protected $guarded = [];
}`

**Comment by gomathisolai16** [comment]
It got fixed after changing  use Shanmuga\LaravelEntrust\Middleware\EntrustRole; to 
use Shanmuga\LaravelEntrust\Models\EntrustRole;

am not seeing this in document, that's why I added it wrongly. If not mentioned in the document , could you please add it ?

**Comment by shanmuga3** [comment]
Role and Permission model is auto generated when you run `php artisan laravel-entrust:setup` command. That's why it is not added in the documentation.
