### ISSUE TITLE
Warning: Using ${var} in strings is deprecated 

### ISSUE THREAD

**Issue by wayson** [shanmuga3/laravel-entrust#21]
**Describe the bug**
We found the warning message from Logs.

Using ${var} in strings is deprecated, use {$var} instead in /var/www/html/vendor/shanmuga/laravel-entrust/src/Commands/MakeMigrationCommand.php on line 164

**To Reproduce**
1. Install docker desktop
2. Pull docker image php:8.2-apache
3. Create a fresh Laravel 10 application
4. Install "shanmuga/laravel-entrust": "^4.1" via composer
5. Run the hello world

**Expected behavior**
No warning.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Amazon Linux 2 in Elastic Beanstalk

**Comment by shanmuga3** [comment]
This issue is fixed, You can use main source to get updated
