### ISSUE TITLE
Laravel 8 LaravelEntrustSeeder

### ISSUE THREAD

**Issue by alibori** [shanmuga3/laravel-entrust#3]
Hi!

In Laravel 8 when you do:

`php artisan laravel-entrust:setup`

It creates the seeder into a "seeds" folder instead of "seeders" folder, so when you do:

`php artisan db:seed`

It doesn't works.

I solved this moving the file to "seeders" folder and, in addition, attaching this line at the beginning of the file:

`namespace Database\Seeders;`

It works for me but I don't know that if it's a good solution.

Thanks!

**Comment by shanmuga3** [comment]
Hi,
   Laravel 8 Support Improved. You can Use Version 2.0. It Will generate both Model and Seed on new namespace.
