### ISSUE TITLE
Imcompatible with PHP 8 and Laravel 8

### ISSUE THREAD

**Issue by RaFaTEOLI** [shanmuga3/laravel-entrust#5]
My composer.json looks like these:

```
"require": {
        "php": "^7.4|^8.0",
        "facade/ignition": "^2.3.6",
        "fakerphp/faker": "^1.13",
        "fideloper/proxy": "^4.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "laravel/legacy-factories": "^1.1",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^3.0"
    },
```

Whenever I try `composer require shanmuga/laravel-entrust`
I get:

[InvalidArgumentException]                                                                                                      
  Package shanmuga/laravel-entrust has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

My composer version is 2 btw.

**Comment by nagibmahfuj** [comment]
@RaFaTEOLI:  See. #6

**Comment by shanmuga3** [comment]
Thank you. Pull request is merged, You can use master source to get updated
