### ISSUE TITLE
Support for multiple guards

### ISSUE THREAD

**Issue by RaFaTEOLI** [shanmuga3/laravel-entrust#7]
It would be really helpful if we could use two guards, api and web at the same time.
```
"defaults" => [
        "guard" => "web",
    ],
```
This would be something like:

```
"defaults" => [
        "guard" => ["web", "api"],
    ],
```

**Comment by RaFaTEOLI** [comment]
I created a pull request to solve this => https://github.com/shanmuga3/laravel-entrust/pull/8

**Comment by shanmuga3** [comment]
Hi RaFaTEOLI,
Thank you. Pull request is now merged.
